#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

#categorie_service:
#  path: /categorie_service
#  controller: App\Controller\CloudCategorieServiceController::ajouter

#categorie_service_edit_modal:
#  path: /categorie_service/{id}/edit
#  controller: App\Controller\CloudCompteControllers\Params\CloudCategorieServiceController::modifier
