<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13gaEWa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13gaEWa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container13gaEWa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container13gaEWa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container13gaEWa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '13gaEWa',
    'container.build_id' => 'bec15f20',
    'container.build_time' => 1581336272,
], __DIR__.\DIRECTORY_SEPARATOR.'Container13gaEWa');
