<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQfs0xR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQfs0xR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHQfs0xR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHQfs0xR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHQfs0xR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HQfs0xR',
    'container.build_id' => 'be5b1922',
    'container.build_time' => 1581170606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQfs0xR');
